"""Reject Bench v7 도메인 계약 (T1).

spec: `.dryforge/spec.md` §3(도메인 모델), §4(저장·보안), §6(지표), §7(검증).
"""

from rejectbench.dataset import Dataset, Violation
from rejectbench.hashing import canonical_json, content_hash, value_hash
from rejectbench.metrics import (
    Completion,
    Status,
    decidable_event_ids,
    decision_completion,
    operation_event_ids,
    review_status,
    verdict_status,
)
from rejectbench.origin import (
    ORIGIN_FIELD,
    OriginTransitionError,
    amend_origin,
    decide_origin,
    validate_origin_transition,
)
from rejectbench.records import (
    SCHEMA_VERSION,
    ActionSummary,
    Amendment,
    CaptureStatus,
    Decision,
    EnforcementRef,
    GuardDecision,
    GuardEvent,
    GuardSpec,
    LossKind,
    LossRecord,
    Origin,
    OriginEvidence,
    PolicyVerdict,
    Record,
    SchemaError,
    Utility,
    UtilityReview,
    Verdict,
    record_from_json,
    to_json,
)
from rejectbench.registry import (
    EnforcementScriptError,
    GuardRegistry,
    QualityError,
    RegisterResult,
    RegistryError,
    SpecReferenceError,
    UnknownSpecError,
    VersionConflictError,
    check_quality,
    enforcement_ref_for,
)
from rejectbench.store import (
    AppendStore,
    CorruptLine,
    LoadResult,
    open_production_store,
    production_root,
)

__all__ = [
    "SCHEMA_VERSION",
    "ORIGIN_FIELD",
    "ActionSummary",
    "Amendment",
    "AppendStore",
    "CaptureStatus",
    "Completion",
    "CorruptLine",
    "Dataset",
    "Decision",
    "EnforcementRef",
    "EnforcementScriptError",
    "GuardDecision",
    "GuardEvent",
    "GuardRegistry",
    "GuardSpec",
    "LoadResult",
    "LossKind",
    "LossRecord",
    "Origin",
    "OriginEvidence",
    "OriginTransitionError",
    "PolicyVerdict",
    "QualityError",
    "Record",
    "RegisterResult",
    "RegistryError",
    "SchemaError",
    "SpecReferenceError",
    "Status",
    "UnknownSpecError",
    "Utility",
    "UtilityReview",
    "Verdict",
    "VersionConflictError",
    "Violation",
    "amend_origin",
    "canonical_json",
    "check_quality",
    "content_hash",
    "decidable_event_ids",
    "decide_origin",
    "decision_completion",
    "enforcement_ref_for",
    "open_production_store",
    "operation_event_ids",
    "production_root",
    "record_from_json",
    "review_status",
    "to_json",
    "validate_origin_transition",
    "value_hash",
    "verdict_status",
]
